version: '2'
services:
  web:
    build:
      context: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
    working_dir: '/usr/src/app'
    command: [bundle, exec, rackup, '-o', '0.0.0.0', '-p', '4567', 'config.ru']
